# Generated by Django 5.0.2 on 2024-02-28 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VwTravelPackage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Travel_Package_Name', models.CharField(max_length=200, null=True)),
                ('Package_Description', models.CharField(max_length=200, null=True)),
                ('Package_Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('LocationID', models.IntegerField(null=True)),
                ('Location_Name', models.CharField(max_length=200, null=True)),
                ('FlightID', models.IntegerField(null=True)),
                ('Flight_Name', models.CharField(max_length=200, null=True)),
                ('HotelRoomID', models.IntegerField(null=True)),
                ('HotelRoom', models.CharField(max_length=200, null=True)),
                ('ActivityID', models.IntegerField(null=True)),
                ('Activity_Name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'vw_TravelPackage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Name', models.CharField(max_length=100, null=True)),
                ('Activity_Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Activity_Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline_name', models.CharField(max_length=200, null=True)),
                ('Airline_description', models.CharField(max_length=200, null=True)),
                ('Airline_Image', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airport_Name', models.CharField(max_length=100, null=True)),
                ('Airport_Address', models.CharField(max_length=100, null=True)),
                ('Airport_Phone', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Category_Name', models.CharField(max_length=50, null=True)),
                ('Flight_Category_Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Name', models.CharField(max_length=200, null=True)),
                ('Hotel_Address', models.CharField(max_length=200, null=True)),
                ('Hotel_Phone', models.CharField(max_length=20, null=True)),
                ('Hotel_Email', models.EmailField(max_length=254)),
                ('Hotel_Amenity', models.CharField(max_length=200, null=True)),
                ('Hotel_Rating', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Hotel_Image', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Name', models.CharField(max_length=100, null=True)),
                ('location_Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Type_Name', models.CharField(max_length=50, null=True)),
                ('Trip_Type_Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Name', models.CharField(max_length=100, null=True)),
                ('Flight_Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Departure_Date', models.DateTimeField(null=True)),
                ('Rerun_Date', models.DateTimeField(null=True)),
                ('Airline_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.airlines')),
                ('Flight_Category_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.flightcategories')),
                ('Going_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='going_to', to='TravelPackages.airports')),
                ('Leaving_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaving_from', to='TravelPackages.airports')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price_Per_Night', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Room_Description', models.CharField(max_length=200, null=True)),
                ('Room_Image', models.CharField(max_length=200, null=True)),
                ('Hotel_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.hotels')),
                ('Room_Type_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.roomtypes')),
                ('Room_Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.statustypes')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Travel_Package_Name', models.CharField(max_length=200, null=True)),
                ('Package_Price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Package_Description', models.CharField(max_length=200, null=True)),
                ('Activity_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.activities')),
                ('Flight_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.flights')),
                ('Hotel_Rooms_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.hotelrooms')),
                ('Location_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelPackages.locations')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpackages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
