# Generated by Django 5.0.1 on 2024-04-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelPackages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwBookingInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Card_Number', models.IntegerField(null=True)),
                ('Expiry_Date', models.DateField(null=True)),
                ('CVC_Number', models.IntegerField(null=True)),
                ('Payment_Amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Booking_Date', models.DateTimeField(null=True)),
                ('Travel_Package_Name', models.CharField(max_length=200, null=True)),
                ('Location_Name', models.CharField(max_length=200, null=True)),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'vw_BookingInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwHotelRoom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('HotelRoom', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'vw_HotelRooms',
                'managed': False,
            },
        ),
    ]
