# Generated by Django 5.0.1 on 2024-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelConcordia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
