# Generated by Django 5.0.1 on 2024-02-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelConcordia', '0002_flight_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='agent',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
