# Generated by Django 5.0.1 on 2024-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelConcordia', '0003_alter_agent_password_alter_agent_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
