# Generated by Django 5.0.1 on 2024-02-26 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelConcordia', '0005_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='price',
            new_name='price_cad',
        ),
        migrations.RenameField(
            model_name='custompackage',
            old_name='total_cost',
            new_name='total_cost_cad',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_price',
            new_name='flight_price_cad',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='price_per_night',
            new_name='price_per_night_cad',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_cad',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='revenue',
            new_name='revenue_cad',
        ),
        migrations.RenameField(
            model_name='travelpackage',
            old_name='total_cost',
            new_name='total_cost_cad',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),

        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),


        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),

    ]
