# Generated by Django 5.0.2 on 2024-02-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PackageManagementApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('activities', models.ManyToManyField(to='PackageManagementApi.activity')),
                ('flights', models.ManyToManyField(to='PackageManagementApi.flight')),
                ('hotels', models.ManyToManyField(to='PackageManagementApi.hotel')),
            ],
        ),
    ]
